global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: bot
    static_configs:
      - targets: ['bot:9100']       # контейнерное имя

  # Qdrant тоже имеет /metrics
  - job_name: qdrant
    static_configs:
      - targets: ['qdrant:6333']

  # PostgreSQL (по желанию)
  - job_name: postgres
    static_configs:
      - targets: ['postgres_exporter:9187']

  - job_name: node
    static_configs:
      - targets: [ 'node_exporter:9101' ]

  - job_name: cadvisor
    static_configs:
      - targets: [ 'cadvisor:8080' ]