from .services.base import get_session
from .services.lessons import LessonService
from .services.ml_gateway import MLGateway
from .services.quiz import QuizService
from .services.direction import DirectionService
from .services.progress import ProgressService
from .services.scenario_analytics import ScenarioAnalytics
from .services.scenario_loader import *
from .config import settings
